database:
  type: postgres
  dsn: postgres://user:pass@localhost:5432/appdb?sslmode=disable
broker:
  type: rabbitmq
  url: amqp://guest:guest@localhost:5672/
poll_interval: 10s
batch_size: 100
max_retries: 5
retry_backoff: 2s
dead_letter_topic: dead-letter-topic
observability:
  service_name: test-service
  tracing_url: jaeger:4318
  metrics_url: otel-collector:9090