receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  jaeger:
    endpoint: "http://jaeger:14250" # Send traces to Jaeger via gRPC

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [zipkin]