version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672" # Management UI
  outbox-sidecar:
    image: myorg/outbox-sidecar:1.0.0
    depends_on:
      - db
      - rabbitmq
    environment:
      SIDECAR_DATABASE_TYPE: "postgres"
      SIDECAR_DATABASE_DSN: "host=db user=user password=pass dbname=appdb sslmode=disable"
      SIDECAR_BROKER_TYPE: "rabbitmq"
      SIDECAR_BROKER_URL: "amqp://guest:guest@rabbitmq:5672/"
      SIDECAR_POLL_INTERVAL: "5s"

volumes:
  postgres_data: