name: PR Build & Test
permissions:
  contents: read
  pull-requests: write
on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/sidecart/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: create workspace
        run: go work init ./sidecart

      - name: add schema to workspace
        run: go work use ./schema
        

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build -o outbox-sidecar ./sidecart/...

      - name: Run unit tests
        run: go test -v ./...
